# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: ambari-lite pre-commit build

on:
  push:
      branches:
        - master
      paths-ignore:
        - '**.md'
  pull_request:
      branches:
        - master
      paths-ignore:
        - '**.md'
  workflow_dispatch:
      inputs:
          MAVEN_OPTS:
            description: 'MAVEN_OPTS' 
env:
  MAVEN_OPTS: -Dmaven.artifact.threads=30 -Dmaven.wagon.http.retryHandler.count=3


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B ${{ github.event.inputs.MAVEN_OPTS }} clean package rpm:rpm -DskipTests -Drat.skip -Dpython.ver="python >= 2.6" --file pom.xml